version: "3"
services:
  api:
    build: .
    image: fastapi-boilerplate
    ports:
      - "8000:8000"
    volumes:
      - .:/src
    environment:
      APP_NAME: knowtify-api
      MONGODB_URL: "mongodb://mongo:27017"
